{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2014-1859",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
        },
        {
          "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
        },
        {
          "url": "http://www.securityfocus.com/bid/65440"
        },
        {
          "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317"
        },
        {
          "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
        },
        {
          "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
        },
        {
          "url": "https://github.com/numpy/numpy/pull/4262"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "(1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-01-08T19:29Z",
  "lastModifiedDate": "2018-01-08T19:29Z"
}