{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2017-15126",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=384632e67e0829deb8015ee6ad916b180049d252"
        },
        {
          "url": "https://access.redhat.com/security/cve/CVE-2017-15126"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1523481"
        },
        {
          "url": "https://github.com/torvalds/linux/commit/384632e67e0829deb8015ee6ad916b180049d252"
        },
        {
          "url": "https://www.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.13.6"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A use-after-free flaw was found in fs/userfaultfd.c in the Linux kernel before 4.13.6. The issue is related to the handling of fork failure when dealing with event messages. Failure to fork correctly can lead to a situation where a fork event will be removed from an already freed list of events with userfaultfd_ctx_put()."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2018-01-14T06:29Z",
  "lastModifiedDate": "2018-01-14T06:29Z"
}